In [10]:
import torch

In [61]:
class Neuron:
    def __init__(self, nin):
        self.w = torch.randn(nin)
        self.b = torch.randn(1)

    def __call__(self, x):
        act = x @ self.w + self.b
        return act.tanh()

class Layer:
    def __init__(self, nin, nout):
        self.neurons = [Neuron(nin) for _ in range(nout)]

    def __call__(self, x):
        outs = [n(x) for n in self.neurons]
        return torch.cat(outs)

class MLP:
    def __init__(self, nin, nouts):
        sz = [nin] + nouts
        self.layers = [Layer(sz[i], sz[i+1]) for i in range(len(nouts))]

    def __call__(self, x):
        for layer in self.layers:
            x = layer(x)
        return x

In [66]:
n = Neuron(2)
print(n(torch.tensor([1.0, 2.0])))
print(n(torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])))

tensor([-0.1507])
tensor([-0.1507,  0.0138,  0.1776])


In [62]:
x = Layer(2, 3)
res = x(torch.tensor([2,4]).float())
print(res)

tensor([ 0.9525, -0.6168,  0.9776])


In [63]:
x = MLP(2, [3,3,1])
res = x(torch.tensor([2,4]).float())
print(res)

tensor([-0.6861])


In [ ]:
X = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]).float()
y = torch.tensor([4, 7, 0]).float()

In [ ]:
W = torch.randn(3)
b = torch.randn(3)
parameters = [W, b]
for parameter in parameters:
    parameter.requires_grad = True

In [ ]:
lr = 0.1
for _ in torch.arange(100):
    for parameter in parameters:
        parameter.grad = None

    h = W @ X + b
    p = torch.atan(h)
    loss = torch.sum(torch.abs(p - y))
    loss.backward()

    for parameter in parameters:
        W -= lr * parameter.grad

In [ ]:
with torch.no_grad():
    z = W @ X + b
    p = z.tanh()
    print(p)